# Generated by Django 4.1.13 on 2024-01-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidelines', '0002_alter_folder_parent_alter_guideline_folderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='content',
        ),
        migrations.AddField(
            model_name='folder',
            name='content',
            field=models.ManyToManyField(to='guidelines.document'),
        ),
    ]
