# Generated by Django 4.1.13 on 2024-01-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidelines', '0003_remove_folder_content_folder_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='childrens',
            field=models.ManyToManyField(blank=True, related_name='parent', to='guidelines.folder'),
        ),
    ]
