# Generated by Django 4.1.13 on 2024-01-14 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guidelines', '0004_folder_childrens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='childrens',
        ),
        migrations.AddField(
            model_name='folder',
            name='children',
            field=models.ManyToManyField(blank=True, to='guidelines.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='guidelines.folder'),
        ),
    ]
