# Generated by Django 4.1.13 on 2024-01-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidelines', '0005_remove_folder_childrens_folder_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='content',
            field=models.ManyToManyField(blank=True, to='guidelines.document'),
        ),
        migrations.RemoveField(
            model_name='folder',
            name='parent',
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ManyToManyField(blank=True, to='guidelines.folder'),
        ),
    ]
