# Generated by Django 4.1.13 on 2024-01-14 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidelines', '0006_alter_folder_content_remove_folder_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='children',
        ),
    ]
