# Generated by Django 4.1.13 on 2024-01-14 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidelines', '0008_remove_folder_parent_folder_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guideline',
            old_name='folderId',
            new_name='folder',
        ),
    ]
