# Generated by Django 4.1.13 on 2024-01-14 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guidelines', '0009_rename_folderid_guideline_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='content',
        ),
        migrations.AddField(
            model_name='folder',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='guidelines.document'),
        ),
    ]
